export const departFromWelcomePage = "DEPART_FROM_WELCOME_PAGE";
export const arrivalAtWelcomePage = "ARRIVAL_AT_WELCOME_PAGE";

export const AUTH_TYPES = {
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",
  VERIFY_USER: "VERIFY_USER",
};

export const ALERT_TYPES = {
  RESET_ALERT: "RESET_ALERT",
  SUCCESS_ALERT: "SUCCESS_ALERT",
  ERROR_ALERT: "ERROR_ALERT",
  RESET_LOGIN_ALERT: "RESET_LOGIN_ALERT",
  RESET_SIGNUP_ALERT: "RESET_SIGNUP_ALERT",
  RESET_LOGOUT_ALERT: "RESET_LOGOUT_ALERT",
  LOGIN_FAILED_ALERT: "LOGIN_FAILED_ALERT",
  SIGNUP_FAILED_ALERT: "SIGNUP_FAILED_ALERT",
  LOGOUT_FAILED_ALERT: "LOGOUT_FAILED_ALERT",
  SUCCESSFULL_SIGNUP_ALERT: "SUCCESSFULL_SIGNUP_ALERT",
  SUCCESSFULL_LOGIN_ALERT: "SUCCESSFULL_LOGIN_ALERT",
  SUCCESSFULL_LOGOUT_ALERT: "SUCCESSFULL_LOGOUT_ALERT",
  SUCCESSFULL_LOAD_USER: "SUCCESSFULL_LOAD_USER",
  FAILED_LOAD_USER: "FAILED_LOAD_USER",
  SUCCESSFUL_UPDATE_USER: "SUCCESSFUL_UPDATE_USER",
  FAILED_UPDATE_USER: "FAILED_UPDATE_USER",
  FAILED_LOAD_USER_GROUPS: "FAILED_LOAD_USER_GROUPS",
  SUCCESSFULL_LOAD_USER_GROUPS: "SUCCESSFULL_LOAD_USER_GROUPS",
};

export const GROUP_TYPES = {
  SEARH_USER: "SEARCH_USER",
  GROUPS_LOADED: "GROUPS_LOADED",
  DELETE_GROUP: "DELETE_GROUP",
  GROUP_CREATED: "GROUP_CREATED",
  RESET_GROUP_CREATED: "RESET_GROUP_CREATED",
  REMOVE_USER: 'REMOVE_USER',
};

export const PROFILE_TYPES = {
  LOAD_PROFILE: "LOAD_PROFILE",
  LOAD_USER_GROUPS: "LOAD_USER_GROUPS",
  PROFILE_UPDATED: "PROFILE_UPDATED",
  RESET_PROFILE_UPDATED: "RESET_PROFILE_UPDATED",
};

export const INVITE_TYPES = {
  LOAD_SENT_INVITES: 'LOAD_SENT_INVITES',
  LOAD_RECEIVED_INVITES: 'LOAD_RECEIVED_INVITES',
  CANCEL_INVITE: 'CANCEL_INVITE',
  ACCEPT_INVITE: 'ACCEPT_INVITE',
  DECLINE_INVITE: 'DECLINE_INVITE',
};

export const POKERBOARD_TYPES = {
  LOAD_POKERBOARD: 'LOAD_POKERBOARD',
  LOAD_POKER: 'LOAD_POKER',
  LOAD_POKER_USERS: 'LOAD_POKER_USERS',
  REMOVE_POKER_USER: 'REMOVE_POKER_USER',
}
