export const departFromWelcomePage = 'DEPART_FROM_WELCOME_PAGE';
export const arrivalAtWelcomePage = 'ARRIVAL_AT_WELCOME_PAGE';

export const AUTH_TYPES = {
    LOGIN_USER: 'LOGIN_USER',
    LOGOUT_USER: 'LOGOUT_USER',
};

export const ALERT_TYPES = {
    RESET_LOGIN_ALERT: 'RESET_LOGIN_ALERT',
    RESET_SIGNUP_ALERT: 'RESET_SIGNUP_ALERT',
    RESET_LOGOUT_ALERT: 'RESET_LOGOUT_ALERT',
    LOGIN_FAILED_ALERT: 'LOGIN_FAILED_ALERT',
    SIGNUP_FAILED_ALERT: 'SIGNUP_FAILED_ALERT',
    LOGOUT_FAILED_ALERT: 'LOGOUT_FAILED_ALERT',
    SUCCESSFULL_SIGNUP_ALERT: 'SUCCESSFULL_SIGNUP_ALERT',
    SUCCESSFULL_LOGIN_ALERT: 'SUCCESSFULL_LOGIN_ALERT',
    SUCCESSFULL_LOGOUT_ALERT: 'SUCCESSFULL_LOGOUT_ALERT',
    SUCCESSFULL_LOAD_USER: 'SUCCESSFULL_LOAD_USER',
    FAILED_LOAD_USER: 'FAILED_LOAD_USER',
    SUCCESSFUL_UPDATE_USER: 'SUCCESSFUL_UPDATE_USER',
    FAILED_UPDATE_USER: 'FAILED_UPDATE_USER',
};

export const PROFILE_TYPES = {
    LOAD_PROFILE: 'LOAD_PROFILE'
}
