export const departFromWelcomePage = 'DEPART_FROM_WELCOME_PAGE';
export const arrivalAtWelcomePage = 'ARRIVAL_AT_WELCOME_PAGE';

export const AUTH_TYPES = {
    LOGIN_USER: 'LOGIN_USER',
    LOGOUT_USER: 'LOGOUT_USER',
};

export const ALERT_TYPES = {
    RESET_ALERT: 'RESET_ALERT',
    SUCCESS_ALERT: 'SUCCESS_ALERT',
    ERROR_ALERT: 'ERROR_ALERT',
    RESET_LOGIN_ALERT: 'RESET_LOGIN_ALERT',
    RESET_SIGNUP_ALERT: 'RESET_SIGNUP_ALERT',
    RESET_LOGOUT_ALERT: 'RESET_LOGOUT_ALERT',
    LOGIN_FAILED_ALERT: 'LOGIN_FAILED_ALERT',
    SIGNUP_FAILED_ALERT: 'SIGNUP_FAILED_ALERT',
    LOGOUT_FAILED_ALERT: 'LOGOUT_FAILED_ALERT',
    SUCCESSFULL_SIGNUP_ALERT: 'SUCCESSFULL_SIGNUP_ALERT',
    SUCCESSFULL_LOGIN_ALERT: 'SUCCESSFULL_LOGIN_ALERT',
    SUCCESSFULL_LOGOUT_ALERT: 'SUCCESSFULL_LOGOUT_ALERT',
};

export const GROUP_TYPES = {
    SEARH_USER: 'SEARCH_USER',
    GROUPS_LOADED: 'GROUPS_LOADED',
}

